In [1]:
import os
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import LeaveOneOut, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## New data

In [2]:
label_dict = {4:0, 5:1}

In [3]:
X_train = pd.read_csv("../data/HAPT/Train/X_train.txt", header=None, sep=" ")
y = pd.read_csv("../data/HAPT/Train/y_train.txt", header=None).rename(columns={0:"label"})
X_train["label"] = y.label
X_train = X_train.sample(frac=1.).reset_index(drop=True)

X_test = pd.read_csv("../data/HAPT/Test/X_test.txt", header=None, sep=" ")
y = pd.read_csv("../data/HAPT/Test/y_test.txt", header=None).rename(columns={0:"label"})
X_test["label"] = y.label 

In [4]:
X_train.shape, X_test.shape

((7767, 562), (3162, 562))

In [5]:
np.unique(X_train.label, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([1226, 1073,  987, 1293, 1423, 1413,   47,   23,   75,   60,   90,
          57]))

In [6]:
train_idx = X_train.label.isin([4,5])
np.unique(X_train[train_idx].label, return_counts=True)

(array([4, 5]), array([1293, 1423]))

In [7]:
# Sitting vs standing
train_idx = X_train.label.isin([4,5])
X_train = X_train[train_idx].reset_index(drop=True)
X_train["label"] = X_train["label"].map(label_dict)

test_idx = X_test.label.isin([4,5])
X_test = X_test[test_idx].reset_index(drop=True)
X_test["label"] = X_test["label"].map(label_dict)
y_test = X_test["label"]

In [8]:
X_train.shape, X_test.shape

((2716, 562), (1064, 562))

In [9]:
np.unique(X_train.label, return_counts=True)

(array([0, 1]), array([1293, 1423]))

In [10]:
X_train.head()

0         1         2         3         4         5         6  \
0  0.040243 -0.002684 -0.020638 -0.996505 -0.996423 -0.994309 -0.996900   
1  0.027705 -0.019720 -0.039006 -0.963102 -0.950293 -0.930569 -0.967610   
2  0.040181 -0.001511 -0.013540 -0.997022 -0.992382 -0.991907 -0.996929   
3  0.041542  0.004941 -0.017991 -0.996213 -0.979937 -0.967548 -0.996299   
4  0.043116  0.008285 -0.017163 -0.980197 -0.965350 -0.983871 -0.983203   

          7         8         9        10        11        12        13  \
0 -0.995687 -0.994611 -0.799694 -0.751905 -0.717516  0.837553  0.715361   
1 -0.951663 -0.942195 -0.758632 -0.720020 -0.647611  0.813254  0.681866   
2 -0.992441 -0.992986 -0.800077 -0.747659 -0.708102  0.839602  0.709361   
3 -0.980631 -0.971401 -0.797031 -0.730051 -0.699154  0.839132  0.701355   
4 -0.966786 -0.986774 -0.776009 -0.707561 -0.706783  0.822611  0.705043   

         14        15        16        17        18        19        20  \
0  0.678068 -0.997548 -0.999980 -0.999981 -0.999947 -0.996691 -0.995407   
1  0.639756 -0.945777 -0.999089 -0.998525 -0.997503 -0.974564 -0.960328   
2  0.678118 -0.995456 -0.999983 -0.999945 -0.999876 -0.996492 -0.993616   
3  0.652492 -0.983637 -0.999972 -0.999683 -0.999437 -0.995467 -0.983328   
4  0.665657 -0.980047 -0.999726 -0.999257 -0.999795 -0.987187 -0.970954   

         21        22        23        24        25        26        27  \
0 -0.994355 -0.705828 -0.715289 -0.640649  0.428270 -0.148116  0.278691   
1 -0.951223 -0.574080 -0.609239 -0.578016 -0.235298 -0.017428  0.281536   
2 -0.995080 -0.680556 -0.611606 -0.410001  0.130097  0.111693 -0.226873   
3 -0.971254 -0.638426 -0.335584 -0.389344  0.255029 -0.064427  0.106454   
4 -0.988586 -0.387587 -0.215438 -0.436610  0.015868 -0.022078  0.052859   

         28        29        30        31        32        33        34  \
0  0.036127  0.422815 -0.283304  0.348060  0.042574  0.361628 -0.084547   
1 -0.286037  0.095854 -0.378997  0.409105  0.093442 -0.065393  0.003585   
2  0.121198  0.422627 -0.239387  0.200146  0.230696  0.249419 -0.131726   
3 -0.135059 -0.145501  0.005704  0.299828 -0.265108 -0.033506  0.164625   
4  0.123321  0.023309 -0.131320  0.016676  0.516341  0.175860  0.041897   

         35        36        37        38        39        40        41  \
0  0.170821 -0.038616  0.207362 -0.126003 -0.059313  0.864398 -0.344069   
1 -0.005194  0.113306  0.649457  0.928481  0.543064  0.808253 -0.226803   
2  0.315551 -0.420664 -0.218135  0.340959  0.140308  0.931432 -0.031449   
3 -0.113274 -0.166229 -0.050865 -0.219672  0.570950  0.931584 -0.284899   
4 -0.016885  0.052488 -0.418668 -0.296465  0.460401  0.918522 -0.330221   

         42        43        44        45        46        47        48  \
0 -0.243635 -0.998780 -0.999368 -0.999097 -0.998913 -0.999416 -0.999103   
1 -0.449244 -0.948806 -0.952960 -0.932947 -0.953637 -0.952613 -0.937934   
2 -0.252802 -0.998501 -0.996467 -0.994996 -0.998495 -0.996669 -0.995623   
3  0.107579 -0.996125 -0.980300 -0.978497 -0.996284 -0.979589 -0.978464   
4  0.095379 -0.992814 -0.979093 -0.993259 -0.992994 -0.979350 -0.992968   

         49        50        51        52        53        54        55  \
0  0.794177 -0.367750 -0.250326  0.889534 -0.316061 -0.241643  0.382838   
1  0.754187 -0.240019 -0.436706  0.792605 -0.217020 -0.491979  0.504867   
2  0.860902 -0.061994 -0.256331  0.954987 -0.008922 -0.251580 -0.316514   
3  0.862167 -0.305161  0.102416  0.954349 -0.262503  0.100223 -0.044194   
4  0.851083 -0.346034  0.087525  0.940933 -0.305973  0.094968  0.021665   

         56        57        58        59        60        61        62   63  \
0  0.648454 -0.787413 -0.877008 -0.999241 -0.999668 -0.999042 -1.000000 -1.0   
1  0.513596 -0.911337 -0.590182 -0.960780 -0.952976 -0.945533 -0.126955 -1.0   
2  0.817245 -0.999378 -0.867799 -0.998479 -0.997598 -0.996936 -1.000000 -1.0   
3  0.817638 -0.856690 -0.979466 -0.996533 -0.979128 -0.980023 -0.831857 -1.0   
4 

# Logreg

In [11]:
def get_predictions(x):
    return [1 if xi >= 0.5 else 0 for xi in x]

In [12]:
X, y = X_train[[col for col in X_train.columns if col != "label"]].values , X_train.label

In [13]:
X.shape, y.shape

((2716, 561), (2716,))

In [14]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[train_index, :], X[test_index,:]
    _y_train = y[train_index].values
    clf = LogisticRegression(random_state=0, C=1., max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

/Users/viktortorpthomsen/opt/anaconda3/envs/dont_overfit_env/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Models AUC score: 0.9926888880555278
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1293
           1       0.97      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [25]:
# Logreg MLE
log_reg = LogisticRegression(random_state=0, C=1.0, max_iter = 500).fit(X[:561,:], y[:561])

In [26]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test)[:,1]

In [27]:
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.9808955984818445


## Small logreg model

In [18]:
sort_idx = np.argsort(np.abs(log_reg.coef_))
sort_coef_vals = np.abs(log_reg.coef_)[0][sort_idx[0]]

In [19]:
len(sort_coef_vals[sort_coef_vals > 0.1])

197

In [20]:
feature_idx = sort_idx[0][-195:]

In [21]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[:,feature_idx][train_index], X[:,feature_idx][test_index]
    _y_train = y[train_index]
    clf = LogisticRegression(random_state=0, C=1., max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

Models AUC score: 0.9925252956755631
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1293
           1       0.96      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [22]:
# Logreg MLE
log_reg = LogisticRegression(random_state=0, C=1.0, max_iter = 500).fit(X[:561,feature_idx], y[:561])

In [23]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test[:,feature_idx])[:,1]

In [24]:
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.9794652467002776


# Gaussian logreg

## MAP l2 estimate C=0.3

In [28]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[train_index, :], X[test_index,:]
    _y_train = y[train_index].values
    clf = LogisticRegression(random_state=0, C=.3, max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

Models AUC score: 0.9909078507493998
              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1293
           1       0.96      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [29]:
log_reg = LogisticRegression(random_state=0, C=.3, penalty="l2", max_iter = 500).fit(X[:561,:], y[:561])

In [30]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test)[:,1]
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.9823011669404633


## Small MAP logreg model

In [31]:
sort_idx = np.argsort(np.abs(log_reg.coef_))
sort_coef_vals = np.abs(log_reg.coef_)[0][sort_idx[0]]

In [20]:
feature_idx = sort_idx[0][-195:]

In [34]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[:,feature_idx][train_index], X[:,feature_idx][test_index]
    _y_train = y[train_index]
    clf = LogisticRegression(random_state=0, C=.3, penalty="l2", max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

Models AUC score: 0.990836109240578
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1293
           1       0.96      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [35]:
# Logreg MLE
log_reg = LogisticRegression(random_state=0, C=.3, penalty="l2", max_iter=500).fit(X[:561,feature_idx], y[:561])

In [36]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test[:,feature_idx])[:,1]

In [37]:
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.9799538322098227


In [28]:
X_test.shape

(271, 195)

# Slap-and-spike prior

In [29]:
X, y = X_train[[col for col in X_train.columns if col != "label"]].values , X_train.label

In [30]:
import pymc3 as pm
import theano as tt
from scipy.special import expit
from scipy.stats import norm, bernoulli

This is our slab and spike model

$$a \sim \mathcal{N}(0, 3)$$
$$\gamma_i \sim Bernoulli(p=0.1)$$
$$\alpha_i|\sigma_\beta \sim \mathcal{N}(0, \sigma_\beta)$$
$$e \sim \mathcal{N}(0, \sigma^2_eI_n)$$
$$y \sim \frac{1}{1+exp(-(a + \sum_{i=1}^N \gamma_i \alpha_i x_i + e))}$$

The model parameters are $\theta = \{\gamma_i, \alpha_i\}_i^N $. The $\gamma_i$ and $\alpha_i$ are modelled IID.

In [31]:
prob = 0.1
a_mu = 0
a_var = 3
gamma_var = 1
with pm.Model() as model:
    # priors inclusion probability
    gamma_i = pm.Bernoulli("gamma_i", prob, shape=X.shape[1])
    # a is the interception
    a = pm.Normal("a", mu=a_mu, sd=a_var)
    # The prior for the features varibles which are included
    alpha = pm.Normal("alpha", mu=0, sd=gamma_var, shape=X.shape[1])
    # Deterministic function
    p = pm.math.dot(X,gamma_i * alpha) 
    # Likelihood
    y_obs = pm.Bernoulli("y_obs", pm.invlogit(p + a),  observed=y)
 

In [32]:
with model:
    trace = pm.sample(2000, random_seed = 4816, cores = 1, progressbar = True, chains = 1)
    

/var/folders/bx/2b_70g054qg3qt5jhnw30xv40000gn/T/ipykernel_47018/2955332559.py:2: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(2000, random_seed = 4816, cores = 1, progressbar = True, chains = 1)
Sequential sampling (1 chains in 1 job)
CompoundStep
>BinaryGibbsMetropolis: [gamma_i]
>NUTS: [alpha, a]


Sampling 1 chain for 1_000 tune and 2_000 draw iterations (1_000 + 2_000 draws total) took 2142 seconds.
There were 24 divergences after tuning. Increase `target_accept` or reparameterize.
Only one chain was sampled, this makes it impossible to run some convergence checks


# Map estimate

The log loss for the spike and slap prior
$$p(\theta) = p(\{\gamma_i, \alpha_i\}_i^N) = \prod_{i=1}^N p(\gamma_i) p(\alpha_i)$$

$$\log p(\theta) = \sum_{i=1}^N \log Bernoulli(\gamma_i | p=0.1) + \log \mathcal{N}(\alpha_i | \mu=0, \sigma_\beta=3)$$

In [33]:
def spike_slab_log_prior(gamma: np.array, alpha: np.array, p, gamma_mu=0, sigma_beta=3):
    return (bernoulli.logpmf(gamma, p=p) + norm.logpdf(alpha, loc=gamma_mu, scale=sigma_beta)).sum()

The negative log likelihood function, i.e. cross entropy

$$E(\mathbf{w}) = -log(p(\pmb{\mathbf{t}}|\pmb{\mathbf{x}},\mathbf{w})) \nonumber$$

$$= - \sum_{n=1}^N \left( t_n \ln y(\mathbf{x}_n) + (1-t_n) \ln (1-y(\mathbf{x}_n)) \right)$$
  

In [34]:
def log_likelihood(a, gamma, alpha, X, T):
    y_x = expit(a + np.dot(X, np.transpose(gamma*alpha)))
    return (T*np.log(y_x) + ((1-T)*np.log(1-y_x))).sum()

In [35]:
prob = 0.1
gamma_mu = 0
sigma_beta = 3

def find_spike_slab_MAP(trace, X, y, prob, gamma_mu, sigma_beta):
    min_loss = np.inf
    cur_min = -1
    for i in range(len(trace)):
        tmp_trace = trace[i]
        tmp_spike_slab_log_prior = spike_slab_log_prior(tmp_trace["gamma_i"], tmp_trace["alpha"], p=prob, gamma_mu=gamma_mu, sigma_beta=sigma_beta)
        tmp_log_likelihood = log_likelihood(tmp_trace["a"], tmp_trace["gamma_i"], tmp_trace["alpha"], X, y)
        neq_loss = -(tmp_log_likelihood + tmp_spike_slab_log_prior)
        if neq_loss <= min_loss:
            min_loss = neq_loss
            cur_min = i
    return trace[cur_min]
    

In [36]:
map_trace = find_spike_slab_MAP(trace, X, y, prob, gamma_mu, sigma_beta)

In [37]:
map_estimate = map_trace["gamma_i"] * map_trace["alpha"]

_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
map_preds = expit(map_trace["a"] + np.dot(_X_test, np.transpose(map_estimate)))

In [47]:
print(f"Models AUC score: {roc_auc_score(y_test, map_preds)}")

Models AUC score: 0.9642659887837761


# Full Bayesian

In [39]:
results = pd.DataFrame({'var': np.arange(561), 
                        'inclusion_probability':np.apply_along_axis(np.mean, 0, trace['gamma_i']),
                       'alpha':np.apply_along_axis(np.mean, 0, trace['alpha']),
                       'alpha_given_inclusion': np.apply_along_axis(np.sum, 0, trace['gamma_i']*trace['alpha'])
                            /np.apply_along_axis(np.sum, 0, trace['gamma_i'])
                       })

In [40]:
results.sort_values('inclusion_probability', ascending = False).head(10)


var  inclusion_probability     alpha  alpha_given_inclusion
41    41                 1.0000 -3.883960              -3.883960
451  451                 1.0000 -2.267181              -2.267181
182  182                 1.0000  5.423177               5.423177
142  142                 1.0000  1.571083               1.571083
50    50                 1.0000 -4.035479              -4.035479
445  445                 1.0000  4.380210               4.380210
186  186                 1.0000 -3.663025              -3.663025
187  187                 0.9970 -2.154221              -2.158809
158  158                 0.9970 -0.996644              -1.002019
53    53                 0.9915 -3.449169              -3.479308

## Bayesian inference

In [41]:
estimate = trace['alpha'] * trace['gamma_i'] 
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
preds = np.apply_along_axis(np.mean, 1, expit(trace['a'] + np.dot(_X_test, np.transpose(estimate) )) )


In [42]:
print(f"Models AUC score: {roc_auc_score(y_test, preds)}")

Models AUC score: 0.9731986064691553


In [43]:
preds[:10]

array([0.99728329, 0.95677686, 0.92627129, 0.96335403, 0.97437116,
       0.94798007, 0.89826115, 0.83813811, 0.84503151, 0.9424179 ])

In [44]:
map_preds[:10]

array([0.99377665, 0.9638406 , 0.86181986, 0.90449025, 0.98654351,
       0.9787043 , 0.94709745, 0.91942937, 0.89949213, 0.92160971])

In [45]:
(map_preds[map_preds > 0.5]).mean(), (map_preds[map_preds <= 0.5]).mean()

(0.9363551762776625, 0.09595969172622476)

In [46]:
(preds[preds > 0.5]).mean(), (preds[preds <= 0.5]).mean()

(0.9245190406644662, 0.09512387902157081)