In [1]:
import os
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import LeaveOneOut, KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## New data

In [2]:
label_dict = {4:0, 5:1}

In [3]:
X_train = pd.read_csv("../data/HAPT/Train/X_train.txt", header=None, sep=" ")
y = pd.read_csv("../data/HAPT/Train/y_train.txt", header=None).rename(columns={0:"label"})
X_train["label"] = y.label
X_train = X_train.sample(frac=1.).reset_index(drop=True)

X_test = pd.read_csv("../data/HAPT/Test/X_test.txt", header=None, sep=" ")
y = pd.read_csv("../data/HAPT/Test/y_test.txt", header=None).rename(columns={0:"label"})
X_test["label"] = y.label 

In [4]:
X_train.shape, X_test.shape

((7767, 562), (3162, 562))

In [5]:
np.unique(X_train.label, return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([1226, 1073,  987, 1293, 1423, 1413,   47,   23,   75,   60,   90,
          57]))

In [6]:
train_idx = X_train.label.isin([4,5])
np.unique(X_train[train_idx].label, return_counts=True)

(array([4, 5]), array([1293, 1423]))

In [7]:
# Sitting vs standing
train_idx = X_train.label.isin([4,5])
X_train = X_train[train_idx].reset_index(drop=True)
X_train["label"] = X_train["label"].map(label_dict)

test_idx = X_test.label.isin([4,5])
X_test = X_test[test_idx].reset_index(drop=True)
X_test["label"] = X_test["label"].map(label_dict)
y_test = X_test["label"]

In [8]:
X_train.shape, X_test.shape

((2716, 562), (1064, 562))

In [9]:
np.unique(X_train.label, return_counts=True)

(array([0, 1]), array([1293, 1423]))

In [10]:
X_train.head()

0         1         2         3         4         5         6  \
0  0.038216 -0.005712 -0.021914 -0.998348 -0.995431 -0.991390 -0.998184   
1  0.040137  0.001698 -0.017681 -0.997485 -0.991863 -0.993166 -0.997438   
2  0.037051 -0.009297 -0.022510 -0.990393 -0.942027 -0.983337 -0.990804   
3  0.038887 -0.003339 -0.023784 -0.988175 -0.970379 -0.978091 -0.989349   
4  0.038962 -0.005479 -0.019209 -0.995611 -0.992720 -0.988614 -0.995954   

          7         8         9        10        11        12        13  \
0 -0.995155 -0.992187 -0.802836 -0.750945 -0.718481  0.840957  0.714987   
1 -0.991411 -0.993787 -0.802697 -0.744286 -0.711083  0.840612  0.716274   
2 -0.941414 -0.985294 -0.794692 -0.708248 -0.711440  0.832721  0.684123   
3 -0.972932 -0.979569 -0.792247 -0.727862 -0.701384  0.827421  0.701815   
4 -0.992431 -0.990926 -0.798141 -0.750187 -0.697104  0.835059  0.711894   

         14        15        16        17        18        19        20  \
0  0.676839 -0.996569 -0.999992 -0.999961 -0.999906 -0.997285 -0.995487   
1  0.680904 -0.995353 -0.999987 -0.999911 -0.999932 -0.996760 -0.992074   
2  0.660024 -0.975509 -0.999915 -0.998568 -0.999779 -0.990658 -0.947044   
3  0.667247 -0.982640 -0.999890 -0.999576 -0.999666 -0.990886 -0.979459   
4  0.671851 -0.995027 -0.999974 -0.999940 -0.999877 -0.995885 -0.992593   

         21        22        23        24        25        26        27  \
0 -0.991556 -0.867607 -0.796640 -0.642749  0.217886 -0.085428 -0.018600   
1 -0.993783 -0.731574 -0.522422 -0.537528  0.200689  0.016174 -0.027804   
2 -0.987508 -0.661743 -0.372098 -0.571696 -0.155275  0.220172 -0.350097   
3 -0.977819 -0.588125 -0.451449 -0.527560  0.292545 -0.103881  0.126498   
4 -0.993535 -0.728058 -0.764401 -0.557118  0.126991  0.100894 -0.076227   

         28        29        30        31        32        33        34  \
0  0.231355  0.230877 -0.180679  0.130887 -0.000333  0.296732 -0.093821   
1 -0.095348  0.076919 -0.126469  0.235319  0.017128  0.533860 -0.280178   
2  0.316497 -0.077798 -0.090272  0.235847  0.023607  0.244782 -0.140568   
3  0.552032 -0.051083  0.098124  0.003004  0.481057  0.187473 -0.017717   
4  0.188700  0.257897 -0.171075  0.237579  0.029195  0.369416 -0.123947   

         35        36        37        38        39        40        41  \
0  0.079359 -0.121715  0.440605  0.375685  0.309766  0.923927 -0.307083   
1  0.366596 -0.154321  0.422118  0.177119  0.353690  0.919337 -0.326731   
2  0.074908  0.264005  0.631290 -0.303732  0.015101  0.926658 -0.326912   
3  0.012110  0.158893  0.422295 -0.022545  0.539373  0.955256 -0.208394   
4  0.159765 -0.338084 -0.067570 -0.251453 -0.155579  0.958810 -0.071728   

         42        43        44        45        46        47        48  \
0 -0.059027 -0.997500 -0.995701 -0.991339 -0.997468 -0.995527 -0.991098   
1  0.103024 -0.997432 -0.991783 -0.996377 -0.997545 -0.991995 -0.996228   
2  0.009950 -0.995397 -0.981858 -0.987664 -0.995549 -0.981922 -0.987426   
3 -0.066481 -0.999976 -0.992557 -0.984442 -0.999968 -0.992729 -0.985988   
4  0.146778 -0.997152 -0.994818 -0.991758 -0.997166 -0.994738 -0.992288   

         49        50        51        52        53        54        55  \
0  0.853679 -0.330423 -0.064355  0.947448 -0.280199 -0.058973 -0.097368   
1  0.849275 -0.347784  0.094138  0.942725 -0.300708  0.103821  0.034169   
2  0.857031 -0.346202  0.005146  0.948406 -0.304859  0.008758 -0.200278   
3  0.883774 -0.233742 -0.064617  0.978749 -0.184813 -0.066887 -0.286354   
4  0.888702 -0.100614  0.138637  0.981423 -0.048625  0.144319 -0.468517   

         56        57        58        59        60        61        62   63  \
0  0.797939 -0.832331 -0.991688 -0.997583 -0.995815 -0.991202 -1.000000 -1.0   
1  0.786183 -0.809129 -0.981306 -0.997854 -0.992786 -0.995942 -1.000000 -1.0   
2  0.804953 -0.808888 -0.999951 -0.995953 -0.982735 -0.986883 -0.742841 -1.0   
3  0.879214 -0.926125 -0.989651 -0.999963 -0.993792 -0.991926 -1.000000 -1.0   
4 

# Logreg

In [11]:
def get_predictions(x):
    return [1 if xi >= 0.5 else 0 for xi in x]

In [12]:
X, y = X_train[[col for col in X_train.columns if col != "label"]].values , X_train.label

In [13]:
X.shape, y.shape

((2716, 561), (2716,))

In [15]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[train_index, :], X[test_index,:]
    _y_train = y[train_index].values
    clf = LogisticRegression(random_state=0, C=1., max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

Models AUC score: 0.9930524870661473
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1293
           1       0.96      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [16]:
# Logreg MLE
log_reg = LogisticRegression(random_state=0, C=1.0, max_iter = 500).fit(X[:561,:], y[:561])

In [17]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test)[:,1]

In [18]:
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.974823684359599


# Gaussian logreg

## MAP l2 estimate C=0.3

In [19]:
loo = KFold(n_splits=10)
preds = np.zeros(len(y))
for i, (train_index, test_index) in enumerate(loo.split(X)):
    _X_train, _X_test = X[train_index, :], X[test_index,:]
    _y_train = y[train_index].values
    clf = LogisticRegression(random_state=0, C=.3, max_iter=500).fit(_X_train, _y_train)
    preds[test_index] = clf.predict_proba(_X_test)[:,1]

print(f"Models AUC score: {roc_auc_score(y, preds)}")
print(classification_report(y, get_predictions(preds)))

Models AUC score: 0.9914823263162529
              precision    recall  f1-score   support

           0       0.95      0.96      0.95      1293
           1       0.96      0.96      0.96      1423

    accuracy                           0.96      2716
   macro avg       0.96      0.96      0.96      2716
weighted avg       0.96      0.96      0.96      2716



In [20]:
log_reg = LogisticRegression(random_state=0, C=.3, penalty="l2", max_iter = 500).fit(X[:561,:], y[:561])

In [21]:
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
y_pred = log_reg.predict_proba(_X_test)[:,1]
print(f"Models AUC score: {roc_auc_score(y_test, y_pred)}")

Models AUC score: 0.9766293264600917


# Slap-and-spike prior

In [29]:
X, y = X_train[[col for col in X_train.columns if col != "label"]].values , X_train.label

In [30]:
import pymc3 as pm
import theano as tt
from scipy.special import expit
from scipy.stats import norm, bernoulli

This is our slab and spike model

$$a \sim \mathcal{N}(0, 3)$$
$$\gamma_i \sim Bernoulli(p=0.1)$$
$$\alpha_i|\sigma_\beta \sim \mathcal{N}(0, \sigma_\beta)$$
$$e \sim \mathcal{N}(0, \sigma^2_eI_n)$$
$$y \sim \frac{1}{1+exp(-(a + \sum_{i=1}^N \gamma_i \alpha_i x_i + e))}$$

The model parameters are $\theta = \{\gamma_i, \alpha_i\}_i^N $. The $\gamma_i$ and $\alpha_i$ are modelled IID.

In [31]:
prob = 0.1
a_mu = 0
a_var = 3
gamma_var = 1
with pm.Model() as model:
    # priors inclusion probability
    gamma_i = pm.Bernoulli("gamma_i", prob, shape=X.shape[1])
    # a is the interception
    a = pm.Normal("a", mu=a_mu, sd=a_var)
    # The prior for the features varibles which are included
    alpha = pm.Normal("alpha", mu=0, sd=gamma_var, shape=X.shape[1])
    # Deterministic function
    p = pm.math.dot(X,gamma_i * alpha) 
    # Likelihood
    y_obs = pm.Bernoulli("y_obs", pm.invlogit(p + a),  observed=y)
 

In [32]:
with model:
    trace = pm.sample(2000, random_seed = 4816, cores = 1, progressbar = True, chains = 1)
    

/var/folders/bx/2b_70g054qg3qt5jhnw30xv40000gn/T/ipykernel_47018/2955332559.py:2: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(2000, random_seed = 4816, cores = 1, progressbar = True, chains = 1)
Sequential sampling (1 chains in 1 job)
CompoundStep
>BinaryGibbsMetropolis: [gamma_i]
>NUTS: [alpha, a]


Sampling 1 chain for 1_000 tune and 2_000 draw iterations (1_000 + 2_000 draws total) took 2142 seconds.
There were 24 divergences after tuning. Increase `target_accept` or reparameterize.
Only one chain was sampled, this makes it impossible to run some convergence checks


# Map estimate

The log loss for the spike and slap prior
$$p(\theta) = p(\{\gamma_i, \alpha_i\}_i^N) = \prod_{i=1}^N p(\gamma_i) p(\alpha_i)$$

$$\log p(\theta) = \sum_{i=1}^N \log Bernoulli(\gamma_i | p=0.1) + \log \mathcal{N}(\alpha_i | \mu=0, \sigma_\beta=3)$$

In [33]:
def spike_slab_log_prior(gamma: np.array, alpha: np.array, p, gamma_mu=0, sigma_beta=3):
    return (bernoulli.logpmf(gamma, p=p) + norm.logpdf(alpha, loc=gamma_mu, scale=sigma_beta)).sum()

The negative log likelihood function, i.e. cross entropy

$$E(\mathbf{w}) = -log(p(\pmb{\mathbf{t}}|\pmb{\mathbf{x}},\mathbf{w})) \nonumber$$

$$= - \sum_{n=1}^N \left( t_n \ln y(\mathbf{x}_n) + (1-t_n) \ln (1-y(\mathbf{x}_n)) \right)$$
  

In [34]:
def log_likelihood(a, gamma, alpha, X, T):
    y_x = expit(a + np.dot(X, np.transpose(gamma*alpha)))
    return (T*np.log(y_x) + ((1-T)*np.log(1-y_x))).sum()

In [35]:
prob = 0.1
gamma_mu = 0
sigma_beta = 3

def find_spike_slab_MAP(trace, X, y, prob, gamma_mu, sigma_beta):
    min_loss = np.inf
    cur_min = -1
    for i in range(len(trace)):
        tmp_trace = trace[i]
        tmp_spike_slab_log_prior = spike_slab_log_prior(tmp_trace["gamma_i"], tmp_trace["alpha"], p=prob, gamma_mu=gamma_mu, sigma_beta=sigma_beta)
        tmp_log_likelihood = log_likelihood(tmp_trace["a"], tmp_trace["gamma_i"], tmp_trace["alpha"], X, y)
        neq_loss = -(tmp_log_likelihood + tmp_spike_slab_log_prior)
        if neq_loss <= min_loss:
            min_loss = neq_loss
            cur_min = i
    return trace[cur_min]
    

In [36]:
map_trace = find_spike_slab_MAP(trace, X, y, prob, gamma_mu, sigma_beta)

In [37]:
map_estimate = map_trace["gamma_i"] * map_trace["alpha"]

_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
map_preds = expit(map_trace["a"] + np.dot(_X_test, np.transpose(map_estimate)))

In [47]:
print(f"Models AUC score: {roc_auc_score(y_test, map_preds)}")

Models AUC score: 0.9642659887837761


# Full Bayesian

In [39]:
results = pd.DataFrame({'var': np.arange(561), 
                        'inclusion_probability':np.apply_along_axis(np.mean, 0, trace['gamma_i']),
                       'alpha':np.apply_along_axis(np.mean, 0, trace['alpha']),
                       'alpha_given_inclusion': np.apply_along_axis(np.sum, 0, trace['gamma_i']*trace['alpha'])
                            /np.apply_along_axis(np.sum, 0, trace['gamma_i'])
                       })

In [40]:
results.sort_values('inclusion_probability', ascending = False).head(10)


var  inclusion_probability     alpha  alpha_given_inclusion
41    41                 1.0000 -3.883960              -3.883960
451  451                 1.0000 -2.267181              -2.267181
182  182                 1.0000  5.423177               5.423177
142  142                 1.0000  1.571083               1.571083
50    50                 1.0000 -4.035479              -4.035479
445  445                 1.0000  4.380210               4.380210
186  186                 1.0000 -3.663025              -3.663025
187  187                 0.9970 -2.154221              -2.158809
158  158                 0.9970 -0.996644              -1.002019
53    53                 0.9915 -3.449169              -3.479308

## Bayesian inference

In [41]:
estimate = trace['alpha'] * trace['gamma_i'] 
_X_test = X_test[[col for col in X_test.columns if col != "label"]].values
preds = np.apply_along_axis(np.mean, 1, expit(trace['a'] + np.dot(_X_test, np.transpose(estimate) )) )


In [42]:
print(f"Models AUC score: {roc_auc_score(y_test, preds)}")

Models AUC score: 0.9731986064691553


In [43]:
preds[:10]

array([0.99728329, 0.95677686, 0.92627129, 0.96335403, 0.97437116,
       0.94798007, 0.89826115, 0.83813811, 0.84503151, 0.9424179 ])

In [44]:
map_preds[:10]

array([0.99377665, 0.9638406 , 0.86181986, 0.90449025, 0.98654351,
       0.9787043 , 0.94709745, 0.91942937, 0.89949213, 0.92160971])

In [45]:
(map_preds[map_preds > 0.5]).mean(), (map_preds[map_preds <= 0.5]).mean()

(0.9363551762776625, 0.09595969172622476)

In [46]:
(preds[preds > 0.5]).mean(), (preds[preds <= 0.5]).mean()

(0.9245190406644662, 0.09512387902157081)